version: '3.8'

services:
  php:
    build: .
    container_name: php_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql